INSERT INTO tickets (title, description, contact_info, status)
VALUES
  ('Ticket 1', 'Description for Ticket 1', '{"name": "John Doe", "email": "john.doe@example.com", "phone": "123-456-7890"}', 'pending'),
  ('Ticket 2', 'Description for Ticket 2', '{"name": "Jane Smith", "email": "jane.smith@example.com", "phone": "234-567-8901"}', 'accepted'),
  ('Ticket 3', 'Description for Ticket 3', '{"name": "Alice Johnson", "email": "alice.johnson@example.com", "phone": "345-678-9012"}', 'resolved'),
  ('Ticket 4', 'Description for Ticket 4', '{"name": "Bob Brown", "email": "bob.brown@example.com", "phone": "456-789-0123"}', 'rejected'),
  ('Ticket 5', 'Description for Ticket 5', '{"name": "Emma Davis", "email": "emma.davis@example.com", "phone": "567-890-1234"}', 'deleted'),
  ('Ticket 6', 'Description for Ticket 6', '{"name": "Michael Wilson", "email": "michael.wilson@example.com", "phone": "678-901-2345"}', 'pending'),
  ('Ticket 7', 'Description for Ticket 7', '{"name": "Olivia Martinez", "email": "olivia.martinez@example.com", "phone": "789-012-3456"}', 'accepted'),
  ('Ticket 8', 'Description for Ticket 8', '{"name": "James Taylor", "email": "james.taylor@example.com", "phone": "890-123-4567"}', 'resolved'),
  ('Ticket 9', 'Description for Ticket 9', '{"name": "Sophia Anderson", "email": "sophia.anderson@example.com", "phone": "901-234-5678"}', 'rejected'),
  ('Ticket 10', 'Description for Ticket 10', '{"name": "William Thomas", "email": "william.thomas@example.com", "phone": "012-345-6789"}', 'deleted'),
  ('Ticket 11', 'Description for Ticket 11', '{"name": "Charlotte Garcia", "email": "charlotte.garcia@example.com", "phone": "123-456-7890"}', 'pending'),
  ('Ticket 12', 'Description for Ticket 12', '{"name": "Daniel Rodriguez", "email": "daniel.rodriguez@example.com", "phone": "234-567-8901"}', 'accepted'),
  ('Ticket 13', 'Description for Ticket 13', '{"name": "Mia Martinez", "email": "mia.martinez@example.com", "phone": "345-678-9012"}', 'resolved'),
  ('Ticket 14', 'Description for Ticket 14', '{"name": "Alexander Lee", "email": "alexander.lee@example.com", "phone": "456-789-0123"}', 'rejected'),
  ('Ticket 15', 'Description for Ticket 15', '{"name": "Emily Harris", "email": "emily.harris@example.com", "phone": "567-890-1234"}', 'deleted'),
  ('Ticket 16', 'Description for Ticket 16', '{"name": "Jacob Clark", "email": "jacob.clark@example.com", "phone": "678-901-2345"}', 'pending'),
  ('Ticket 17', 'Description for Ticket 17', '{"name": "Isabella Lewis", "email": "isabella.lewis@example.com", "phone": "789-012-3456"}', 'accepted'),
  ('Ticket 18', 'Description for Ticket 18', '{"name": "Ethan Walker", "email": "ethan.walker@example.com", "phone": "890-123-4567"}', 'resolved'),
  ('Ticket 19', 'Description for Ticket 19', '{"name": "Ava Perez", "email": "ava.perez@example.com", "phone": "901-234-5678"}', 'rejected'),
  ('Ticket 20', 'Description for Ticket 20', '{"name": "Michael Young", "email": "michael.young@example.com", "phone": "012-345-6789"}', 'deleted'),
  ('Ticket 21', 'Description for Ticket 21', '{"name": "Abigail Allen", "email": "abigail.allen@example.com", "phone": "123-456-7890"}', 'pending'),
  ('Ticket 22', 'Description for Ticket 22', '{"name": "Elijah Hall", "email": "elijah.hall@example.com", "phone": "234-567-8901"}', 'accepted'),
  ('Ticket 23', 'Description for Ticket 23', '{"name": "Sofia King", "email": "sofia.king@example.com", "phone": "345-678-9012"}', 'resolved'),
  ('Ticket 24', 'Description for Ticket 24', '{"name": "Mason Wright", "email": "mason.wright@example.com", "phone": "456-789-0123"}', 'rejected'),
  ('Ticket 25', 'Description for Ticket 25', '{"name": "Harper Scott", "email": "harper.scott@example.com", "phone": "567-890-1234"}', 'deleted'),
  ('Ticket 26', 'Description for Ticket 26', '{"name": "Evelyn Baker", "email": "evelyn.baker@example.com", "phone": "678-901-2345"}', 'pending'),
  ('Ticket 27', 'Description for Ticket 27', '{"name": "Logan Nelson", "email": "logan.nelson@example.com", "phone": "789-012-3456"}', 'accepted'),
  ('Ticket 28', 'Description for Ticket 28', '{"name": "Chloe Adams", "email": "chloe.adams@example.com", "phone": "890-123-4567"}', 'resolved'),
  ('Ticket 29', 'Description for Ticket 29', '{"name": "Carter Hill", "email": "carter.hill@example.com", "phone": "901-234-5678"}', 'rejected'),
  ('Ticket 30', 'Description for Ticket 30', '{"name": "Liam Baker", "email": "liam.baker@example.com", "phone": "012-345-6789"}', 'deleted'),
  ('Issue with login', 'Cannot login to the system', 'pending', '{"name": "John Doe", "email": "john@example.com", "phone": "+1234567890"}'),
  ('Register not work', 'Cannot register to the system (U will not see me)', 'deleted', '{"name": "Jane Smith", "email": "jane@example.com", "phone": "+1987654321"}'),
  ('Bug in module X', 'Module X crashes unexpectedly', 'accepted', '{"name": "Bob Johnson", "email": "bob@example.com", "phone": "+1555123456"}'),
  ('Feature request', 'Request for adding new feature Y', 'resolved', '{"name": "Alice Jones", "email": "alice@example.com", "phone": "+1444333222"}');
